[tox]
envlist = clean,py-flask3-django{42,52,60},docs,report

[testenv]
usedevelop = true
deps =
    wheel
    coverage
    pytest
    codecov
    aiohttp == 3.14.2
    django42: django == 4.2.30
    django52: django == 5.2.16
    django60: django == 6.0.7
    flask3: flask == 3.1.3
    jinja2
    PyYAML
commands =
    coverage run -m pytest tests --junitxml=.tox/test_report.xml --doctest-modules --strict-markers {posargs}

[testenv:docs]
usedevelop = true
description = invoke sphinx-build to build the HTML docs
deps = sphinx == 9.1.0
    aiohttp == 3.14.2
    django == 6.0.7
    flask == 3.1.3
    jinja2
    PyYAML
commands = 
    sphinx-build -d "{toxworkdir}/docs_doctree" docs "{toxworkdir}/docs_out" -W -bhtml
    
[testenv:clean]
deps = coverage
skip_install = true
commands = coverage erase

[testenv:report]
deps = coverage
skip_install = true
commands =
    coverage report
    coverage xml
    coverage html
